name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'python-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or specify a specific version like 3.9, 3.10, etc.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade twine pip build
        working-directory: ./python # Important: Run these in the python directory.

      - name: Build package
        run: python -m build
        working-directory: ./python

      - name: Publish package to PyPI
        run: twine upload dist/*
        working-directory: ./python
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}